version: 0.0
os: linux
files:
  - source: /
    destination: /opt/survey
  - source: /config/database.yml.production
    destination: /opt/survey/config/database.yml
permissions:
  - object: /opt/survey
    pattern: "**"
    owner: webservice
    group: webservice
    mode: 755
hooks:
  AfterInstall:
    - location: script/codedeploy_bundle
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/codedeploy_start
      timeout: 180
      runas: root
